
version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.8
    restart: unless-stopped
    ports:
      - "5672:5672"
    working_dir: /var/www
    networks:
      - cluster


networks:
  cluster:
    driver: bridge




