
####################
# Parameter Based Routing Example
# Extending on the autorouting example, a new route is added that utilizes parameter based routing.
####################


routes:

  ####################
  # The below route will only accept messages that have a request method of POST, and 
  # and URI ends with /login.
  ####################
  user_login:
    type: rpc
    params:
      method: "== POST"
      uri: "=~ \\/login$"
    routing_keys:
      syrus.template.parse: App\Users\Login


  general.rpc:
    type: rpc
    routing_keys:
      users.profile: 
        default: App\Users\Profiles
        shop: App\Shop\Users
      financial.orders: App\Shop\Orders
      all: App\~package.title~\~module.title~


